#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PLTS.Resource", IsApplication=true)]

namespace PLTS
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::P2PCLIENT.Resource.String.ApplicationName = global::PLTS.Resource.String.ApplicationName;
			global::P2PCLIENT.Resource.String.Hello = global::PLTS.Resource.String.Hello;
			global::ZYSocketClientB.Resource.String.ApplicationName = global::PLTS.Resource.String.ApplicationName;
			global::ZYSocketClientB.Resource.String.Hello = global::PLTS.Resource.String.Hello;
			global::ZYSocketShare.Resource.String.ApplicationName = global::PLTS.Resource.String.ApplicationName;
			global::ZYSocketShare.Resource.String.Hello = global::PLTS.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int button1 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int button2 = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int editText1 = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout2 = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int textView1 = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int MAC = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int MaxPort = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int MinPort = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int ResCount = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int ServerIP = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ServerPort = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int ServerRegPort = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
